### PR TITLE
Experiment processing

### PR DESCRIPTION
**Pull request by mhoover-gallup**
This PR updates #4 and is more extensive in nature. It refactors some of the repository to better deal/associate between empanelment and experiment. It is a mix of R and Python; the R deals with empanelment and experiment processing; the Python deals with automating SMS pushes.

### CODE REVIEW

**Comment by mhoover-gallup** [comment]
@gallupBenRyan I know you don't work on NGS2, but can you provide a quick review on the Python script? Or, LMK and I can come to you and step you through what's needed to understand what's going on.

@pablo-diego-rosell I'll leave the R review to you; I need to push some changes you requested in #4.
* Replacing "W:/" with "//gallup/dod_clients" below works better for me:
  * dd <- "//gallup/dod_clients/DARPA_NGS2/CONSULTING/Analytics/cycle2/data"
  * od <- "//gallup/dod_clients/DARPA_NGS2/CONSULTING/Analytics/cycle2/output"
* Please comment on the rationale for "sdCutoff = 3"
* I would move these instructions to the top, I was confused for example by the missing 'Q107_7' variable until I read this comment. **DONE**

**Comment by gallupBenRyan** [comment]
Sure thing, man. Actually, I’ll swing by momentarily to discuss this and the Pew/Education question from this morning.

**Comment by mhoover-gallup** [comment]
The rationale for `Please comment on the rationale for "sdCutoff = 3"` broadens the scope for matches with the hot deck imputation (from the default value of 1). If you feel more comfortable with the default or some other value, I'm agnostic; I just tried to get as many observations for matching as possible across the variables used.

**Comment by pablo-diego-rosell** [comment]
OK, thanks Matt, good to go!

**Pull request merged**
